# Assume Python 3.10 (oldest supported)
target-version = "py310"

# We have agreed on longer lines
line-length = 120

# Override ruff's default include
# Because notebooks are tougher
include = [ "*.py", "*.pyi", "pyproject.toml" ]
exclude = [
    ".eggs",
    ".git",
]

[lint]
select = [
  # "B",        # flake8-bugbear
  "I",        # isort
  # "ARG",      # flake8-unused-arguments
  # "C4",       # flake8-comprehensions
  # "F401",     # flake8-unused-imports
  # "F541",     # flake8 f-string without any placeholders
  # "BLE001",   # No bare 'except' clauses
  "RUF022",   # Sort __all__
  # "UP007",    # PEP 604 Union[X, Y] -> X | Y
  # "UP045",    # PEP 604 Optional[X] -> X | None
]
